version: '3'
services:
  api:
    image: inno-server
    build: 
       dockerfile: Dockerfile
       context: "./inno-server"
    networks:
      - backend
    ports:
      - "3001:3001"
    volumes:
      - ./:/usr/src/app
 
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    image: inno-client-react
    build: 
       dockerfile: Dockerfile
       context: "./inno-client"
    networks:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
 

networks:
  backend:
    driver: bridge
